# Generated by Django 4.1.1 on 2022-10-09 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('status', models.BooleanField(default=False, help_text='0-Default, 1-Hidden')),
                ('Trending', models.BooleanField(default=False, help_text='0-Default, 1-Trending')),
                ('location', models.CharField(max_length=100)),
                ('hotel_id', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('MenuItem_image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('status', models.BooleanField(default=False, help_text='0-Default, 1-Hidden')),
                ('Trending', models.BooleanField(default=False, help_text='0-Default, 1-Trending')),
                ('Tag', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.hotel')),
            ],
        ),
    ]
