# Generated by Django 4.1.1 on 2022-10-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='category',
            new_name='Restaurant',
        ),
    ]
