# Generated by Django 4.1.1 on 2022-10-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_category_menuitem_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='Restaurant',
            new_name='category',
        ),
    ]
