# Generated by Django 4.1.1 on 2022-10-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='MenuItem_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
